(() => {
const NS="http://www.w3.org/2000/svg",$=id=>document.getElementById(id);
const svg=$("cad"),geometry=$("geometry"),dimensions=$("dimensions"),preview=$("preview"),snapLayer=$("snapLayer"),statusEl=$("status"),coordsEl=$("coords"),commandEl=$("command"),properties=$("properties"),propertyFields=$("propertyFields"),propTitle=$("propTitle"),edgeInfo=$("edgeInfo");
const state={tool:"select",shapes:[],history:[],selectedIds:[],start:null,drawing:false,viewBox:{x:0,y:0,w:1200,h:800},panStart:null,panViewStart:null,pointers:new Map(),pinchStart:null,snapEnabled:true,multi:false,drag:null};
const uid=()=> "s_"+Math.random().toString(36).slice(2,9),num=v=>Number.parseFloat(v)||0,fmt=v=>(Math.round(v*100)/100).toString();
function status(m){statusEl.textContent=m} function snapshot(){state.history.push(JSON.stringify(state.shapes));if(state.history.length>80)state.history.shift()}
function undo(){if(!state.history.length)return;state.shapes=JSON.parse(state.history.pop());state.selectedIds=[];hideProperties();render()}
function svgPoint(cx,cy){const r=svg.getBoundingClientRect();return{x:state.viewBox.x+(cx-r.left)/r.width*state.viewBox.w,y:state.viewBox.y+(cy-r.top)/r.height*state.viewBox.h}}
function tol(px=16){const r=svg.getBoundingClientRect();return state.viewBox.w/Math.max(r.width,1)*px}
function snapCandidates(){const c=[];for(const s of state.shapes){if(s.type==="line")c.push({x:s.x1,y:s.y1,type:"Endpunkt"},{x:s.x2,y:s.y2,type:"Endpunkt"},{x:(s.x1+s.x2)/2,y:(s.y1+s.y2)/2,type:"Mittelpunkt"});
else if(s.type==="rect")c.push({x:s.x,y:s.y,type:"Ecke"},{x:s.x+s.w,y:s.y,type:"Ecke"},{x:s.x,y:s.y+s.h,type:"Ecke"},{x:s.x+s.w,y:s.y+s.h,type:"Ecke"},{x:s.x+s.w/2,y:s.y+s.h/2,type:"Mittelpunkt"});
else if(s.type==="circle")c.push({x:s.cx,y:s.cy,type:"Mittelpunkt"},{x:s.cx+s.r,y:s.cy,type:"Quadrant"},{x:s.cx-s.r,y:s.cy,type:"Quadrant"},{x:s.cx,y:s.cy+s.r,type:"Quadrant"},{x:s.cx,y:s.cy-s.r,type:"Quadrant"})}return c}
function snappedRaw(p){if(!state.snapEnabled)return{...p,type:null};let best=null,bd=Infinity;for(const c of snapCandidates()){const d=Math.hypot(c.x-p.x,c.y-p.y);if(d<tol()&&d<bd){best=c;bd=d}}return best?{...best}:{x:Math.round(p.x/10)*10,y:Math.round(p.y/10)*10,type:"Raster"}}
function setViewBox(){const v=state.viewBox;svg.setAttribute("viewBox",`${v.x} ${v.y} ${v.w} ${v.h}`)}
function el(name,attrs={},cls=""){const e=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(cls)e.setAttribute("class",cls);return e}
function shapeEl(s){let e;if(s.type==="line")e=el("line",{x1:s.x1,y1:s.y1,x2:s.x2,y2:s.y2});if(s.type==="rect")e=el("rect",{x:s.x,y:s.y,width:s.w,height:s.h});if(s.type==="circle")e=el("circle",{cx:s.cx,cy:s.cy,r:s.r});e.classList.add("shape");if(state.selectedIds.includes(s.id))e.classList.add("selected");e.dataset.id=s.id;return e}
function renderDims(){dimensions.replaceChildren();if(state.selectedIds.length!==1)return;const s=findShape(state.selectedIds[0]);if(!s)return;if(s.type==="rect"){let t=el("text",{x:s.x+s.w/2,y:s.y-18,"text-anchor":"middle"},"dim-text");t.textContent=`${fmt(s.w)} mm`;dimensions.append(t);t=el("text",{x:s.x+s.w+20,y:s.y+s.h/2},"dim-text");t.textContent=`${fmt(s.h)} mm`;dimensions.append(t)}
if(s.type==="circle"){const t=el("text",{x:s.cx,y:s.cy-s.r-14,"text-anchor":"middle"},"dim-text");t.textContent=`Ø ${fmt(s.r*2)} mm`;dimensions.append(t)}
if(s.type==="line"){const t=el("text",{x:(s.x1+s.x2)/2,y:(s.y1+s.y2)/2-12,"text-anchor":"middle"},"dim-text");t.textContent=`${fmt(Math.hypot(s.x2-s.x1,s.y2-s.y1))} mm`;dimensions.append(t)}}
function render(){geometry.replaceChildren();state.shapes.forEach(s=>geometry.appendChild(shapeEl(s)));renderDims();setViewBox()}
function renderSnap(s){snapLayer.replaceChildren();if(!state.snapEnabled||!s)return;const r=tol(6);snapLayer.append(el("circle",{cx:s.x,cy:s.y,r},"snap-marker"),el("line",{x1:s.x-r*1.5,y1:s.y,x2:s.x+r*1.5,y2:s.y},"snap-marker"),el("line",{x1:s.x,y1:s.y-r*1.5,x2:s.x,y2:s.y+r*1.5},"snap-marker"))}
function make(tool,a,b){if(tool==="line")return{id:uid(),type:"line",x1:a.x,y1:a.y,x2:b.x,y2:b.y};if(tool==="rect")return{id:uid(),type:"rect",x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(b.x-a.x),h:Math.abs(b.y-a.y)};if(tool==="circle")return{id:uid(),type:"circle",cx:a.x,cy:a.y,r:Math.hypot(b.x-a.x,b.y-a.y)}}
function setTool(t){state.tool=t;document.querySelectorAll(".tool").forEach(b=>b.classList.toggle("active",b.dataset.tool===t));status(`${t} · mm`)}
function findShape(id){return state.shapes.find(s=>s.id===id)}
function hideProperties(){properties.classList.add("hidden");edgeInfo.classList.add("hidden")}
function containingRect(circle){return state.shapes.find(s=>s.type==="rect"&&circle.cx>=s.x&&circle.cx<=s.x+s.w&&circle.cy>=s.y&&circle.cy<=s.y+s.h)}
function updateEdgeInfo(s){edgeInfo.classList.add("hidden");if(!s||s.type!=="circle")return;const r=containingRect(s);if(!r)return;const left=s.cx-r.x,right=r.x+r.w-s.cx,top=s.cy-r.y,bottom=r.y+r.h-s.cy;edgeInfo.innerHTML=`Randabstände Mittelpunkt:<br>Links ${fmt(left)} mm · Rechts ${fmt(right)} mm<br>Oben ${fmt(top)} mm · Unten ${fmt(bottom)} mm`;edgeInfo.classList.remove("hidden")}
function showProperties(){if(state.selectedIds.length===0){hideProperties();return}properties.classList.remove("hidden");propertyFields.replaceChildren();
if(state.selectedIds.length>1){propTitle.textContent=`${state.selectedIds.length} Objekte ausgewählt`;edgeInfo.classList.add("hidden");$("applyProperties").style.display="none";return}
$("applyProperties").style.display="block";const s=findShape(state.selectedIds[0]);if(!s)return;let fields=[];if(s.type==="rect"){propTitle.textContent="Rechteck";fields=[["x","X",s.x],["y","Y",s.y],["w","Breite",s.w],["h","Höhe",s.h]]}
if(s.type==="circle"){propTitle.textContent="Bohrung / Kreis";fields=[["cx","Mittelpunkt X",s.cx],["cy","Mittelpunkt Y",s.cy],["d","Durchmesser",s.r*2]]}
if(s.type==="line"){propTitle.textContent="Linie";fields=[["x1","X1",s.x1],["y1","Y1",s.y1],["x2","X2",s.x2],["y2","Y2",s.y2]]}
for(const[k,l,v]of fields){const w=document.createElement("div");w.className="field";const lab=document.createElement("label");lab.textContent=l+" (mm)";const inp=document.createElement("input");inp.type="number";inp.step="0.1";inp.value=fmt(v);inp.dataset.key=k;w.append(lab,inp);propertyFields.appendChild(w)}updateEdgeInfo(s)}
$("closeProperties").onclick=()=>{state.selectedIds=[];hideProperties();render()};
$("applyProperties").onclick=()=>{if(state.selectedIds.length!==1)return;const s=findShape(state.selectedIds[0]);if(!s)return;snapshot();const v={};propertyFields.querySelectorAll("input").forEach(i=>v[i.dataset.key]=num(i.value));if(s.type==="rect")Object.assign(s,{x:v.x,y:v.y,w:Math.abs(v.w),h:Math.abs(v.h)});if(s.type==="circle")Object.assign(s,{cx:v.cx,cy:v.cy,r:Math.abs(v.d)/2});if(s.type==="line")Object.assign(s,{x1:v.x1,y1:v.y1,x2:v.x2,y2:v.y2});render();showProperties();status("Maße übernommen")}
function selectId(id){if(!id){state.selectedIds=[];hideProperties();render();return}if(state.multi){state.selectedIds=state.selectedIds.includes(id)?state.selectedIds.filter(x=>x!==id):[...state.selectedIds,id]}else state.selectedIds=[id];render();showProperties()}
function del(){if(!state.selectedIds.length)return;snapshot();const set=new Set(state.selectedIds);state.shapes=state.shapes.filter(s=>!set.has(s.id));state.selectedIds=[];hideProperties();render();status("Auswahl gelöscht")}
function translate(s,dx,dy){if(s.type==="rect"){s.x+=dx;s.y+=dy}if(s.type==="circle"){s.cx+=dx;s.cy+=dy}if(s.type==="line"){s.x1+=dx;s.y1+=dy;s.x2+=dx;s.y2+=dy}}
function duplicate(){if(!state.selectedIds.length)return;snapshot();const out=[];for(const id of state.selectedIds){const s=findShape(id);if(!s)continue;const c=JSON.parse(JSON.stringify(s));c.id=uid();translate(c,20,20);state.shapes.push(c);out.push(c.id)}state.selectedIds=out;render();showProperties();status(`${out.length} Objekt(e) dupliziert`)}
function down(e){svg.setPointerCapture?.(e.pointerId);state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
if(state.pointers.size===2){const p=[...state.pointers.values()];state.pinchStart={dist:Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),view:{...state.viewBox}};return}
if(state.tool==="select"){const id=e.target?.dataset?.id||null;if(!id){if(e.target.id==="gridBg")selectId(null);return}selectId(id);if(!state.multi&&state.selectedIds.length===1)state.drag={ids:[...state.selectedIds],start:svgPoint(e.clientX,e.clientY),originals:state.selectedIds.map(x=>JSON.parse(JSON.stringify(findShape(x)))),moved:false};return}
if(state.tool==="pan"){state.panStart={x:e.clientX,y:e.clientY};state.panViewStart={...state.viewBox};return}
if(["line","rect","circle"].includes(state.tool)){const s=snappedRaw(svgPoint(e.clientX,e.clientY));state.start={x:s.x,y:s.y};state.drawing=true;renderSnap(s)}}
function movePointer(e){state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const raw=svgPoint(e.clientX,e.clientY),sp=snappedRaw(raw);coordsEl.textContent=`X ${sp.x.toFixed(1)} · Y ${sp.y.toFixed(1)} mm${sp.type?" · "+sp.type:""}`;renderSnap(sp);
if(state.pointers.size===2&&state.pinchStart){const p=[...state.pointers.values()],d=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),f=state.pinchStart.dist/Math.max(d,1),nw=Math.min(10000,Math.max(50,state.pinchStart.view.w*f)),nh=Math.min(10000,Math.max(50,state.pinchStart.view.h*f)),cx=state.pinchStart.view.x+state.pinchStart.view.w/2,cy=state.pinchStart.view.y+state.pinchStart.view.h/2;state.viewBox={x:cx-nw/2,y:cy-nh/2,w:nw,h:nh};setViewBox();return}
if(state.tool==="select"&&state.drag){const p=svgPoint(e.clientX,e.clientY),dx=p.x-state.drag.start.x,dy=p.y-state.drag.start.y;if(Math.hypot(dx,dy)>tol(3))state.drag.moved=true;state.drag.originals.forEach(o=>{const s=findShape(o.id);Object.assign(s,JSON.parse(JSON.stringify(o)));translate(s,dx,dy)});render();return}
if(state.tool==="pan"&&state.panStart){const r=svg.getBoundingClientRect(),dx=(e.clientX-state.panStart.x)/r.width*state.panViewStart.w,dy=(e.clientY-state.panStart.y)/r.height*state.panViewStart.h;state.viewBox.x=state.panViewStart.x-dx;state.viewBox.y=state.panViewStart.y-dy;setViewBox();return}
if(state.drawing&&state.start){preview.replaceChildren();const pe=shapeEl({...make(state.tool,state.start,{x:sp.x,y:sp.y}),id:"p"});pe.classList.remove("shape");pe.classList.add("preview");preview.appendChild(pe)}}
function up(e){const count=state.pointers.size;state.pointers.delete(e.pointerId);if(count>=2){if(state.pointers.size<2)state.pinchStart=null;return}
if(state.tool==="select"&&state.drag){if(state.drag.moved){const finals=state.drag.ids.map(id=>JSON.parse(JSON.stringify(findShape(id))));state.drag.originals.forEach(o=>Object.assign(findShape(o.id),o));snapshot();finals.forEach(f=>Object.assign(findShape(f.id),f));render();showProperties()}state.drag=null;return}
if(state.tool==="pan"){state.panStart=null;state.panViewStart=null;return}
if(state.drawing&&state.start){const sp=snappedRaw(svgPoint(e.clientX,e.clientY)),s=make(state.tool,state.start,{x:sp.x,y:sp.y});const ok=s&&(s.type==="line"?Math.hypot(s.x2-s.x1,s.y2-s.y1)>.5:s.type==="rect"?s.w>.5&&s.h>.5:s.r>.5);if(ok){snapshot();state.shapes.push(s);state.selectedIds=[s.id]}state.drawing=false;state.start=null;preview.replaceChildren();render();if(ok)showProperties()}}
svg.addEventListener("pointerdown",down);svg.addEventListener("pointermove",movePointer);svg.addEventListener("pointerup",up);svg.addEventListener("pointercancel",up);
document.querySelectorAll(".tool").forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$("undoBtn").onclick=undo;$("deleteBtn").onclick=del;$("duplicateBtn").onclick=duplicate;
$("multiBtn").onclick=()=>{state.multi=!state.multi;$("multiBtn").classList.toggle("active",state.multi);status(state.multi?"Mehrfachauswahl an":"Mehrfachauswahl aus")};
$("snapBtn").onclick=()=>{state.snapEnabled=!state.snapEnabled;$("snapBtn").classList.toggle("active",state.snapEnabled);if(!state.snapEnabled)snapLayer.replaceChildren();status(state.snapEnabled?"Fang aktiviert":"Fang deaktiviert")};
$("newBtn").onclick=()=>{snapshot();state.shapes=[];state.selectedIds=[];hideProperties();render();status("Neues Projekt")};
$("saveBtn").onclick=()=>download("cutai-project.json",JSON.stringify({schema:"cutai-cad/0.3",units:"mm",shapes:state.shapes},null,2),"application/json");
$("loadInput").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(!Array.isArray(p.shapes))throw new Error();snapshot();state.shapes=p.shapes;state.selectedIds=[];hideProperties();render();fitAll();status("Projekt geladen")}catch{status("Projektdatei ungültig")}e.target.value=""};
function download(name,text,type){const blob=new Blob([text],{type}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function fitAll(){if(!state.shapes.length){state.viewBox={x:0,y:0,w:1200,h:800};render();return}const xs=[],ys=[];for(const s of state.shapes){if(s.type==="line"){xs.push(s.x1,s.x2);ys.push(s.y1,s.y2)}if(s.type==="rect"){xs.push(s.x,s.x+s.w);ys.push(s.y,s.y+s.h)}if(s.type==="circle"){xs.push(s.cx-s.r,s.cx+s.r);ys.push(s.cy-s.r,s.cy+s.r)}}const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=Math.max(50,(maxX-minX+maxY-minY)*.08);state.viewBox={x:minX-pad,y:minY-pad,w:Math.max(100,maxX-minX+2*pad),h:Math.max(100,maxY-minY+2*pad)};render()}
$("fitBtn").onclick=fitAll;
function dxfPair(code,value){return `${code}\n${value}\n`}
function dxfLine(x1,y1,x2,y2,layer="0"){return dxfPair(0,"LINE")+dxfPair(8,layer)+dxfPair(10,fmt(x1))+dxfPair(20,fmt(-y1))+dxfPair(30,0)+dxfPair(11,fmt(x2))+dxfPair(21,fmt(-y2))+dxfPair(31,0)}
function dxfCircle(cx,cy,r,layer="0"){return dxfPair(0,"CIRCLE")+dxfPair(8,layer)+dxfPair(10,fmt(cx))+dxfPair(20,fmt(-cy))+dxfPair(30,0)+dxfPair(40,fmt(r))}
function makeDxf(){let out=dxfPair(0,"SECTION")+dxfPair(2,"HEADER")+dxfPair(9,"$ACADVER")+dxfPair(1,"AC1009")+dxfPair(9,"$INSUNITS")+dxfPair(70,4)+dxfPair(0,"ENDSEC")+dxfPair(0,"SECTION")+dxfPair(2,"ENTITIES");
for(const s of state.shapes){if(s.type==="line")out+=dxfLine(s.x1,s.y1,s.x2,s.y2);
else if(s.type==="circle")out+=dxfCircle(s.cx,s.cy,s.r);
else if(s.type==="rect"){out+=dxfLine(s.x,s.y,s.x+s.w,s.y);out+=dxfLine(s.x+s.w,s.y,s.x+s.w,s.y+s.h);out+=dxfLine(s.x+s.w,s.y+s.h,s.x,s.y+s.h);out+=dxfLine(s.x,s.y+s.h,s.x,s.y)}}
out+=dxfPair(0,"ENDSEC")+dxfPair(0,"EOF");return out}
$("dxfBtn").onclick=()=>{if(!state.shapes.length){status("Keine Geometrie für DXF");return}download("cutai-export-r12.dxf",makeDxf(),"application/dxf");status(`${state.shapes.length} CAD-Objekt(e) als DXF exportiert`)};
function runCommand(raw){const cmd=raw.trim();if(!cmd)return;const plate=cmd.match(/(?:platte|rechteck)\s+(\d+(?:[.,]\d+)?)\s*[x×]\s*(\d+(?:[.,]\d+)?)/i);if(!plate){status("Befehl nicht verstanden");return}
const w=parseFloat(plate[1].replace(",",".")),h=parseFloat(plate[2].replace(",",".")),wants4=/\b4\s*(?:x\s*)?(?:bohrungen|löcher)\b/i.test(cmd);
if(wants4){const dm=cmd.match(/(?:ø|⌀|Ø|durchmesser)\s*(\d+(?:[.,]\d+)?)/i),em=cmd.match(/(?:rand|randabstand|abstand)\s*(\d+(?:[.,]\d+)?)/i);const d=dm?parseFloat(dm[1].replace(",",".")):null,edge=em?parseFloat(em[1].replace(",",".")):null;if(!(d>0)||!(edge>=0)){status("Für 4 Bohrungen brauche Ø und Randabstand");return}if(edge>w/2||edge>h/2){status("Randabstand zu groß");return}
snapshot();const p={id:uid(),type:"rect",x:0,y:0,w,h};state.shapes.push(p);[[edge,edge],[w-edge,edge],[edge,h-edge],[w-edge,h-edge]].forEach(([x,y])=>state.shapes.push({id:uid(),type:"circle",cx:x,cy:y,r:d/2}));state.selectedIds=[];hideProperties();render();fitAll();status(`Platte ${w} × ${h} · 4× Ø${d} · Rand ${edge}`);return}
snapshot();state.shapes.push({id:uid(),type:"rect",x:0,y:0,w,h});state.selectedIds=[];hideProperties();render();fitAll();status(`Platte ${w} × ${h} mm erstellt`)}
$("runCommand").onclick=()=>runCommand(commandEl.value);commandEl.addEventListener("keydown",e=>{if(e.key==="Enter")runCommand(commandEl.value)});
render();
})();