(() => {
const NS="http://www.w3.org/2000/svg",$=id=>document.getElementById(id);
const svg=$("cad"),geometry=$("geometry"),dimensions=$("dimensions"),camMarkers=$("camMarkers"),preview=$("preview"),snapLayer=$("snapLayer"),statusEl=$("status"),coordsEl=$("coords"),properties=$("properties"),propertyFields=$("propertyFields"),propTitle=$("propTitle"),edgeInfo=$("edgeInfo"),contourList=$("contourList");
const state={tool:"select",shapes:[],history:[],redo:[],selectedIds:[],start:null,drawing:false,viewBox:{x:0,y:0,w:1200,h:800},panStart:null,panViewStart:null,pointers:new Map(),pinchStart:null,snapEnabled:true,multi:false,drag:null,startPointMode:false};
const uid=()=> "s_"+Math.random().toString(36).slice(2,9),num=v=>Number.parseFloat(v)||0,fmt=v=>(Math.round(v*1000)/1000).toString(),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function status(m){statusEl.textContent=m}
function defaultCam(){return{technology:"Plasma",contourType:"auto",direction:"cw",order:1,leadIn:0,leadOut:0,startPoint:null,bevel:{enabled:false,angle:0,side:"left",type:"V",land:0}}}
function normalize(s){if(!s.id)s.id=uid();if(!s.cam)s.cam=defaultCam();if(!s.cam.bevel)s.cam.bevel={enabled:false,angle:0,side:"left",type:"V",land:0};return s}
function snapshot(){state.history.push(JSON.stringify(state.shapes));if(state.history.length>100)state.history.shift();state.redo=[]}
function undo(){if(!state.history.length){status("Nichts zum Rückgängigmachen");return}state.redo.push(JSON.stringify(state.shapes));state.shapes=JSON.parse(state.history.pop()).map(normalize);state.selectedIds=[];hideProperties();render();status("Rückgängig")}
function redo(){if(!state.redo.length){status("Nichts zum Wiederholen");return}state.history.push(JSON.stringify(state.shapes));state.shapes=JSON.parse(state.redo.pop()).map(normalize);state.selectedIds=[];hideProperties();render();status("Wiederholt")}
function svgPoint(cx,cy){const r=svg.getBoundingClientRect();return{x:state.viewBox.x+(cx-r.left)/r.width*state.viewBox.w,y:state.viewBox.y+(cy-r.top)/r.height*state.viewBox.h}}
function tol(px=16){const r=svg.getBoundingClientRect();return state.viewBox.w/Math.max(r.width,1)*px}
function snapCandidates(){const c=[];for(const s of state.shapes){if(s.type==="line")c.push({x:s.x1,y:s.y1,type:"Endpunkt"},{x:s.x2,y:s.y2,type:"Endpunkt"},{x:(s.x1+s.x2)/2,y:(s.y1+s.y2)/2,type:"Mittelpunkt"});
else if(s.type==="rect")c.push({x:s.x,y:s.y,type:"Ecke"},{x:s.x+s.w,y:s.y,type:"Ecke"},{x:s.x,y:s.y+s.h,type:"Ecke"},{x:s.x+s.w,y:s.y+s.h,type:"Ecke"},{x:s.x+s.w/2,y:s.y+s.h/2,type:"Mittelpunkt"});
else if(s.type==="circle"||s.type==="arc")c.push({x:s.cx,y:s.cy,type:"Mittelpunkt"},{x:s.cx+s.r,y:s.cy,type:"Quadrant"},{x:s.cx-s.r,y:s.cy,type:"Quadrant"},{x:s.cx,y:s.cy+s.r,type:"Quadrant"},{x:s.cx,y:s.cy-s.r,type:"Quadrant"})}return c}
function snappedRaw(p){if(!state.snapEnabled)return{...p,type:null};let best=null,bd=Infinity;for(const c of snapCandidates()){const d=Math.hypot(c.x-p.x,c.y-p.y);if(d<tol()&&d<bd){best=c;bd=d}}return best?{...best}:{x:Math.round(p.x/10)*10,y:Math.round(p.y/10)*10,type:"Raster"}}
function setViewBox(){const v=state.viewBox;svg.setAttribute("viewBox",`${v.x} ${v.y} ${v.w} ${v.h}`)}
function el(name,attrs={},cls=""){const e=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(cls)e.setAttribute("class",cls);return e}
function arcPath(s){const a1=s.startAngle*Math.PI/180,a2=s.endAngle*Math.PI/180,x1=s.cx+s.r*Math.cos(a1),y1=s.cy+s.r*Math.sin(a1),x2=s.cx+s.r*Math.cos(a2),y2=s.cy+s.r*Math.sin(a2);let da=(s.endAngle-s.startAngle)%360;if(da<0)da+=360;return`M ${x1} ${y1} A ${s.r} ${s.r} 0 ${da>180?1:0} 1 ${x2} ${y2}`}
function shapeEl(s){let e;if(s.type==="line")e=el("line",{x1:s.x1,y1:s.y1,x2:s.x2,y2:s.y2});if(s.type==="rect")e=el("rect",{x:s.x,y:s.y,width:s.w,height:s.h});if(s.type==="circle")e=el("circle",{cx:s.cx,cy:s.cy,r:s.r});if(s.type==="arc")e=el("path",{d:arcPath(s)});e.classList.add("shape");if(state.selectedIds.includes(s.id))e.classList.add("selected");e.dataset.id=s.id;return e}
function findShape(id){return state.shapes.find(s=>s.id===id)}
function selectedOne(){return state.selectedIds.length===1?findShape(state.selectedIds[0]):null}
function containingRect(circle){return state.shapes.find(s=>s.type==="rect"&&circle.cx>=s.x&&circle.cx<=s.x+s.w&&circle.cy>=s.y&&circle.cy<=s.y+s.h)}
function resolvedContourType(s){if(s.cam.contourType!=="auto")return s.cam.contourType;if(s.type==="circle")return containingRect(s)?"inside":"outside";if(s.type==="rect")return"outside";return"none"}
function contourLabel(s,i){const names={rect:"Rechteck",circle:"Kreis",line:"Linie",arc:"Bogen"};const type=resolvedContourType(s);const typeName={inside:"Innen",outside:"Außen",mark:"Markieren",drill:"Bohren",none:"Keine"}[type]||"Auto";const bv=s.cam.bevel?.enabled?` · Fase ${fmt(s.cam.bevel.angle)}°`:"";return{title:`${i+1}. ${names[s.type]||s.type}`,meta:`${s.cam.technology} · ${typeName} · Reihenfolge ${s.cam.order}${bv}`}}
function renderContourList(){contourList.replaceChildren();state.shapes.forEach((s,i)=>{const item=document.createElement("button");item.className="contour-item"+(state.selectedIds.includes(s.id)?" selected":"");item.dataset.id=s.id;const l=contourLabel(s,i);item.innerHTML=`<strong>${l.title}</strong><div class="contour-meta">${l.meta}</div>`;item.onclick=()=>{if(state.multi){state.selectedIds=state.selectedIds.includes(s.id)?state.selectedIds.filter(x=>x!==s.id):[...state.selectedIds,s.id]}else state.selectedIds=[s.id];render();showProperties()};contourList.appendChild(item)})}
function renderDims(){dimensions.replaceChildren();const s=selectedOne();if(!s)return;if(s.type==="rect"){let t=el("text",{x:s.x+s.w/2,y:s.y-18,"text-anchor":"middle"},"dim-text");t.textContent=`${fmt(s.w)} mm`;dimensions.append(t);t=el("text",{x:s.x+s.w+20,y:s.y+s.h/2},"dim-text");t.textContent=`${fmt(s.h)} mm`;dimensions.append(t)}
if(s.type==="circle"){const t=el("text",{x:s.cx,y:s.cy-s.r-14,"text-anchor":"middle"},"dim-text");t.textContent=`Ø ${fmt(s.r*2)} mm`;dimensions.append(t)}
if(s.type==="line"){const t=el("text",{x:(s.x1+s.x2)/2,y:(s.y1+s.y2)/2-12,"text-anchor":"middle"},"dim-text");t.textContent=`${fmt(Math.hypot(s.x2-s.x1,s.y2-s.y1))} mm`;dimensions.append(t)}}
function renderCamMarkers(){camMarkers.replaceChildren();for(const s of state.shapes){if(!s.cam?.startPoint)continue;const p=s.cam.startPoint,r=tol(5);camMarkers.append(el("circle",{cx:p.x,cy:p.y,r},"start-marker"));const t=el("text",{x:p.x+r*1.8,y:p.y-r*1.3},"direction-label");t.textContent=s.cam.direction==="cw"?"↻":"↺";camMarkers.append(t)}}
function render(){geometry.replaceChildren();state.shapes.forEach(s=>geometry.appendChild(shapeEl(s)));renderDims();renderCamMarkers();renderContourList();setViewBox()}
function renderSnap(s){snapLayer.replaceChildren();if(!state.snapEnabled||!s)return;const r=tol(6);snapLayer.append(el("circle",{cx:s.x,cy:s.y,r},"snap-marker"),el("line",{x1:s.x-r*1.5,y1:s.y,x2:s.x+r*1.5,y2:s.y},"snap-marker"),el("line",{x1:s.x,y1:s.y-r*1.5,x2:s.x,y2:s.y+r*1.5},"snap-marker"))}
function make(tool,a,b){if(tool==="line")return normalize({type:"line",x1:a.x,y1:a.y,x2:b.x,y2:b.y});if(tool==="rect")return normalize({type:"rect",x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(b.x-a.x),h:Math.abs(b.y-a.y)});if(tool==="circle")return normalize({type:"circle",cx:a.x,cy:a.y,r:Math.hypot(b.x-a.x,b.y-a.y)})}
function setTool(t){state.tool=t;state.startPointMode=false;document.querySelectorAll(".tool").forEach(b=>b.classList.toggle("active",b.dataset.tool===t));status(`${t} · mm`)}
function hideProperties(){properties.classList.add("hidden");edgeInfo.classList.add("hidden")}
function updateEdgeInfo(s){edgeInfo.classList.add("hidden");if(!s||s.type!=="circle")return;const r=containingRect(s);if(!r)return;const left=s.cx-r.x,right=r.x+r.w-s.cx,top=s.cy-r.y,bottom=r.y+r.h-s.cy;edgeInfo.innerHTML=`Auto: Innenkontur<br>Randabstände Mittelpunkt:<br>Links ${fmt(left)} mm · Rechts ${fmt(right)} mm<br>Oben ${fmt(top)} mm · Unten ${fmt(bottom)} mm`;edgeInfo.classList.remove("hidden")}
function setCamInputs(s){$("technology").value=s.cam.technology;$("contourType").value=s.cam.contourType;$("direction").value=s.cam.direction;$("cutOrder").value=s.cam.order;$("leadIn").value=s.cam.leadIn;$("leadOut").value=s.cam.leadOut;$("bevelEnabled").checked=!!s.cam.bevel.enabled;$("bevelAngle").value=fmt(s.cam.bevel.angle);$("bevelSide").value=s.cam.bevel.side;$("bevelType").value=s.cam.bevel.type;$("bevelLand").value=fmt(s.cam.bevel.land)}
function showProperties(){if(state.selectedIds.length===0){hideProperties();return}properties.classList.remove("hidden");propertyFields.replaceChildren();
if(state.selectedIds.length>1){propTitle.textContent=`${state.selectedIds.length} Konturen ausgewählt`;document.querySelector(".cam-fields").style.display="grid";$("applyProperties").style.display="none";$("setStartBtn").style.display="none";$("clearStartBtn").style.display="none";edgeInfo.classList.add("hidden");setCamInputs(findShape(state.selectedIds[0]));return}
document.querySelector(".cam-fields").style.display="grid";$("applyProperties").style.display="block";$("setStartBtn").style.display="block";$("clearStartBtn").style.display="block";
const s=selectedOne();let fields=[];if(s.type==="rect"){propTitle.textContent="Rechteck / Kontur";fields=[["x","X",s.x],["y","Y",s.y],["w","Breite",s.w],["h","Höhe",s.h]]}
if(s.type==="circle"){propTitle.textContent="Kreis / Bohrung";fields=[["cx","Mittelpunkt X",s.cx],["cy","Mittelpunkt Y",s.cy],["d","Durchmesser",s.r*2]]}
if(s.type==="line"){propTitle.textContent="Linie";fields=[["x1","X1",s.x1],["y1","Y1",s.y1],["x2","X2",s.x2],["y2","Y2",s.y2]]}
for(const[k,l,v]of fields){const w=document.createElement("div");w.className="field";const lab=document.createElement("label");lab.textContent=l+" (mm)";const inp=document.createElement("input");inp.type="number";inp.step="0.1";inp.value=fmt(v);inp.dataset.key=k;w.append(lab,inp);propertyFields.appendChild(w)}setCamInputs(s);updateEdgeInfo(s)}
function applyCamFieldsTo(s){const a=clamp(num($("bevelAngle").value),0,50);Object.assign(s.cam,{technology:$("technology").value,contourType:$("contourType").value,direction:$("direction").value,order:Math.max(1,Math.round(num($("cutOrder").value))),leadIn:Math.max(0,num($("leadIn").value)),leadOut:Math.max(0,num($("leadOut").value))});s.cam.bevel={enabled:$("bevelEnabled").checked&&a>0,angle:a,side:$("bevelSide").value,type:$("bevelType").value,land:Math.max(0,num($("bevelLand").value))}}
$("closeProperties").onclick=()=>{state.selectedIds=[];state.startPointMode=false;hideProperties();render()};
$("applyProperties").onclick=()=>{const s=selectedOne();if(!s)return;snapshot();const v={};propertyFields.querySelectorAll("input").forEach(i=>v[i.dataset.key]=num(i.value));if(s.type==="rect")Object.assign(s,{x:v.x,y:v.y,w:Math.abs(v.w),h:Math.abs(v.h)});if(s.type==="circle")Object.assign(s,{cx:v.cx,cy:v.cy,r:Math.abs(v.d)/2});if(s.type==="line")Object.assign(s,{x1:v.x1,y1:v.y1,x2:v.x2,y2:v.y2});applyCamFieldsTo(s);render();showProperties();status("Geometrie übernommen")}
$("applyCamToSelection").onclick=()=>{if(!state.selectedIds.length)return;snapshot();state.selectedIds.forEach(id=>{const s=findShape(id);if(s)applyCamFieldsTo(s)});render();showProperties();status(`CAM/Fase auf ${state.selectedIds.length} Kontur(en) übernommen`)};
function selectId(id){if(!id){state.selectedIds=[];state.startPointMode=false;hideProperties();render();return}if(state.multi)state.selectedIds=state.selectedIds.includes(id)?state.selectedIds.filter(x=>x!==id):[...state.selectedIds,id];else state.selectedIds=[id];render();showProperties()}
function del(){if(!state.selectedIds.length)return;snapshot();const set=new Set(state.selectedIds);state.shapes=state.shapes.filter(s=>!set.has(s.id));state.selectedIds=[];hideProperties();render();status("Auswahl gelöscht")}
function translate(s,dx,dy){if(s.type==="rect"){s.x+=dx;s.y+=dy}if(s.type==="circle"||s.type==="arc"){s.cx+=dx;s.cy+=dy}if(s.type==="line"){s.x1+=dx;s.y1+=dy;s.x2+=dx;s.y2+=dy}if(s.cam?.startPoint){s.cam.startPoint.x+=dx;s.cam.startPoint.y+=dy}}
function moveSelection(dx,dy){if(!state.selectedIds.length)return;snapshot();state.selectedIds.forEach(id=>{const s=findShape(id);if(s)translate(s,dx,dy)});render();showProperties();status(`${state.selectedIds.length} Kontur(en) um ΔX ${fmt(dx)} / ΔY ${fmt(dy)} verschoben`)}
$("moveApply").onclick=()=>moveSelection(num($("moveX").value),num($("moveY").value));
document.querySelectorAll("[data-nudge]").forEach(b=>b.onclick=()=>{const[dx,dy]=b.dataset.nudge.split(",").map(Number);moveSelection(dx,dy)});
function duplicate(){if(!state.selectedIds.length)return;snapshot();const out=[];for(const id of state.selectedIds){const s=findShape(id);if(!s)continue;const c=normalize(JSON.parse(JSON.stringify(s)));c.id=uid();translate(c,20,20);state.shapes.push(c);out.push(c.id)}state.selectedIds=out;render();showProperties();status(`${out.length} Kontur(en) kopiert`)}
function nearestOnSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;if(!l2)return{...a};let t=((p.x-a.x)*dx+(p.y-a.y)*dy)/l2;t=Math.max(0,Math.min(1,t));return{x:a.x+t*dx,y:a.y+t*dy}}
function nearestPointOnShape(s,p){if(s.type==="circle"){const dx=p.x-s.cx,dy=p.y-s.cy,d=Math.hypot(dx,dy)||1;return{x:s.cx+s.r*dx/d,y:s.cy+s.r*dy/d}}if(s.type==="line")return nearestOnSegment(p,{x:s.x1,y:s.y1},{x:s.x2,y:s.y2});if(s.type==="rect"){const edges=[[{x:s.x,y:s.y},{x:s.x+s.w,y:s.y}],[{x:s.x+s.w,y:s.y},{x:s.x+s.w,y:s.y+s.h}],[{x:s.x+s.w,y:s.y+s.h},{x:s.x,y:s.y+s.h}],[{x:s.x,y:s.y+s.h},{x:s.x,y:s.y}]];let best=null,bd=Infinity;for(const[a,b]of edges){const q=nearestOnSegment(p,a,b),d=Math.hypot(q.x-p.x,q.y-p.y);if(d<bd){best=q;bd=d}}return best}return p}
$("setStartBtn").onclick=()=>{if(!selectedOne())return;state.startPointMode=true;status("Gewünschte Startposition auf Kontur antippen")};
$("clearStartBtn").onclick=()=>{const s=selectedOne();if(!s)return;snapshot();s.cam.startPoint=null;state.startPointMode=false;render();status("Startpunkt gelöscht")};
$("bevelZeroBtn").onclick=()=>{$("bevelEnabled").checked=false;$("bevelAngle").value=0;status("Fase aus / 0° vorbereitet")};
$("bevel45Btn").onclick=()=>{$("bevelEnabled").checked=true;$("bevelAngle").value=45;status("Fase 45° vorbereitet")};
$("bevel50Btn").onclick=()=>{$("bevelEnabled").checked=true;$("bevelAngle").value=50;status("Fase 50° vorbereitet")};
$("bevelAngle").addEventListener("change",()=>{const a=clamp(num($("bevelAngle").value),0,50);$("bevelAngle").value=fmt(a);$("bevelEnabled").checked=a>0;status(`Fasenwinkel ${fmt(a)}°`) });


function down(e){svg.setPointerCapture?.(e.pointerId);state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
if(state.pointers.size===2){const p=[...state.pointers.values()];state.pinchStart={dist:Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),view:{...state.viewBox}};return}
if(state.startPointMode){const s=selectedOne();if(s){snapshot();s.cam.startPoint=nearestPointOnShape(s,svgPoint(e.clientX,e.clientY));state.startPointMode=false;render();showProperties();status("Startpunkt gesetzt")}return}
if(state.tool==="select"){const id=e.target?.dataset?.id||null;if(!id){if(e.target.id==="gridBg")selectId(null);return}selectId(id);if(!state.multi&&state.selectedIds.length===1)state.drag={ids:[...state.selectedIds],start:svgPoint(e.clientX,e.clientY),originals:state.selectedIds.map(x=>JSON.parse(JSON.stringify(findShape(x)))),moved:false};return}
if(state.tool==="pan"){state.panStart={x:e.clientX,y:e.clientY};state.panViewStart={...state.viewBox};return}
if(["line","rect","circle"].includes(state.tool)){const s=snappedRaw(svgPoint(e.clientX,e.clientY));state.start={x:s.x,y:s.y};state.drawing=true;renderSnap(s)}}
function movePointer(e){state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const raw=svgPoint(e.clientX,e.clientY),sp=snappedRaw(raw);coordsEl.textContent=`X ${sp.x.toFixed(1)} · Y ${sp.y.toFixed(1)} mm${sp.type?" · "+sp.type:""}`;renderSnap(sp);
if(state.pointers.size===2&&state.pinchStart){const p=[...state.pointers.values()],d=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),f=state.pinchStart.dist/Math.max(d,1),nw=Math.min(10000,Math.max(50,state.pinchStart.view.w*f)),nh=Math.min(10000,Math.max(50,state.pinchStart.view.h*f)),cx=state.pinchStart.view.x+state.pinchStart.view.w/2,cy=state.pinchStart.view.y+state.pinchStart.view.h/2;state.viewBox={x:cx-nw/2,y:cy-nh/2,w:nw,h:nh};setViewBox();return}
if(state.tool==="select"&&state.drag){const p=svgPoint(e.clientX,e.clientY),dx=p.x-state.drag.start.x,dy=p.y-state.drag.start.y;if(Math.hypot(dx,dy)>tol(3))state.drag.moved=true;state.drag.originals.forEach(o=>{const s=findShape(o.id);Object.assign(s,JSON.parse(JSON.stringify(o)));translate(s,dx,dy)});render();return}
if(state.tool==="pan"&&state.panStart){const r=svg.getBoundingClientRect(),dx=(e.clientX-state.panStart.x)/r.width*state.panViewStart.w,dy=(e.clientY-state.panStart.y)/r.height*state.panViewStart.h;state.viewBox.x=state.panViewStart.x-dx;state.viewBox.y=state.panViewStart.y-dy;setViewBox();return}
if(state.drawing&&state.start){preview.replaceChildren();const pe=shapeEl({...make(state.tool,state.start,{x:sp.x,y:sp.y}),id:"p"});pe.classList.remove("shape");pe.classList.add("preview");preview.appendChild(pe)}}
function up(e){const count=state.pointers.size;state.pointers.delete(e.pointerId);if(count>=2){if(state.pointers.size<2)state.pinchStart=null;return}
if(state.tool==="select"&&state.drag){if(state.drag.moved){const finals=state.drag.ids.map(id=>JSON.parse(JSON.stringify(findShape(id))));state.drag.originals.forEach(o=>Object.assign(findShape(o.id),o));snapshot();finals.forEach(f=>Object.assign(findShape(f.id),f));render();showProperties()}state.drag=null;return}
if(state.tool==="pan"){state.panStart=null;state.panViewStart=null;return}
if(state.drawing&&state.start){const sp=snappedRaw(svgPoint(e.clientX,e.clientY)),s=make(state.tool,state.start,{x:sp.x,y:sp.y});const ok=s&&(s.type==="line"?Math.hypot(s.x2-s.x1,s.y2-s.y1)>.5:s.type==="rect"?s.w>.5&&s.h>.5:s.r>.5);if(ok){snapshot();s.cam.order=state.shapes.length+1;state.shapes.push(s);state.selectedIds=[s.id]}state.drawing=false;state.start=null;preview.replaceChildren();render();if(ok)showProperties()}}

svg.addEventListener("pointerdown",down);svg.addEventListener("pointermove",movePointer);svg.addEventListener("pointerup",up);svg.addEventListener("pointercancel",up);
document.querySelectorAll(".tool").forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$("undoBtn").onclick=undo;$("redoBtn").onclick=redo;$("deleteBtn").onclick=del;$("duplicateBtn").onclick=duplicate;
$("multiBtn").onclick=()=>{state.multi=!state.multi;$("multiBtn").classList.toggle("active",state.multi);status(state.multi?"Mehrfachauswahl an":"Mehrfachauswahl aus")};
$("snapBtn").onclick=()=>{state.snapEnabled=!state.snapEnabled;$("snapBtn").classList.toggle("active",state.snapEnabled);if(!state.snapEnabled)snapLayer.replaceChildren();status(state.snapEnabled?"Fang aktiviert":"Fang deaktiviert")};
$("selectAllBtn").onclick=()=>{state.selectedIds=state.shapes.map(s=>s.id);state.multi=true;$("multiBtn").classList.add("active");render();showProperties();status(`${state.selectedIds.length} Konturen ausgewählt`)};
$("clearSelectionBtn").onclick=()=>{state.selectedIds=[];hideProperties();render();status("Auswahl aufgehoben")};

function download(name,text,type){const blob=new Blob([text],{type}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("newBtn").onclick=()=>{snapshot();state.shapes=[];state.selectedIds=[];hideProperties();render();status("Neues Projekt")};
$("saveBtn").onclick=()=>download("cutai-project-v06.json",JSON.stringify({schema:"cutai-cad/0.6",units:"mm",shapes:state.shapes},null,2),"application/json");
$("loadInput").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(!Array.isArray(p.shapes))throw new Error();snapshot();state.shapes=p.shapes.map(normalize);state.selectedIds=[];hideProperties();render();fitAll();status("Projekt geladen")}catch{status("Projektdatei ungültig")}e.target.value=""};

function autoCam(){snapshot();const closed=state.shapes.filter(s=>s.type==="rect"||s.type==="circle");const inside=closed.filter(s=>s.type==="circle"&&containingRect(s)),outside=closed.filter(s=>!inside.includes(s));inside.forEach((s,i)=>{s.cam.contourType="auto";s.cam.order=i+1;s.cam.direction="ccw"});outside.forEach((s,i)=>{s.cam.contourType="auto";s.cam.order=inside.length+i+1;s.cam.direction="cw"});render();showProperties();status(`${inside.length} Innen- und ${outside.length} Außenkontur(en) zugeordnet`)}
$("autoCamBtn").onclick=autoCam;

function fitAll(){if(!state.shapes.length){state.viewBox={x:0,y:0,w:1200,h:800};render();return}const xs=[],ys=[];for(const s of state.shapes){if(s.type==="line"){xs.push(s.x1,s.x2);ys.push(s.y1,s.y2)}if(s.type==="rect"){xs.push(s.x,s.x+s.w);ys.push(s.y,s.y+s.h)}if(s.type==="circle"||s.type==="arc"){xs.push(s.cx-s.r,s.cx+s.r);ys.push(s.cy-s.r,s.cy+s.r)}}const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=Math.max(50,(maxX-minX+maxY-minY)*.08);state.viewBox={x:minX-pad,y:minY-pad,w:Math.max(100,maxX-minX+2*pad),h:Math.max(100,maxY-minY+2*pad)};render()}
$("fitBtn").onclick=fitAll;$("resetViewBtn").onclick=()=>{state.viewBox={x:0,y:0,w:1200,h:800};render();status("Ansicht zurückgesetzt")};

function pairs(text){const lines=text.replace(/\r/g,"").split("\n"),out=[];for(let i=0;i+1<lines.length;i+=2)out.push([lines[i].trim(),lines[i+1].trim()]);return out}
function entityFromPairs(type,data){const g={};for(const[c,v]of data){if(!g[c])g[c]=[];g[c].push(v)}const f=(c,i=0)=>parseFloat(g[c]?.[i]??"0"),layer=g["8"]?.[0]||"0";if(type==="LINE")return normalize({type:"line",x1:f("10"),y1:-f("20"),x2:f("11"),y2:-f("21"),sourceLayer:layer});if(type==="CIRCLE")return normalize({type:"circle",cx:f("10"),cy:-f("20"),r:Math.abs(f("40")),sourceLayer:layer});return null}
function parseDxf(text){const p=pairs(text),entities=[];let inEntities=false,currentType=null,current=[];function flush(){if(currentType){const e=entityFromPairs(currentType,current);if(e)entities.push(e)}currentType=null;current=[]}for(let i=0;i<p.length;i++){const[c,v]=p[i];if(c==="0"&&v==="SECTION"&&p[i+1]?.[0]==="2"&&p[i+1]?.[1]==="ENTITIES"){inEntities=true;i++;continue}if(inEntities&&c==="0"&&v==="ENDSEC"){flush();break}if(!inEntities)continue;if(c==="0"){flush();currentType=v}else current.push([c,v])}return entities}
$("dxfInput").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const shapes=parseDxf(await f.text());if(!shapes.length)throw new Error();snapshot();state.shapes.push(...shapes);state.selectedIds=[];hideProperties();fitAll();status(`${shapes.length} DXF-Element(e) importiert`)}catch{status("DXF konnte nicht gelesen werden")}e.target.value=""};

function parseSvg(text){const doc=new DOMParser().parseFromString(text,"image/svg+xml"),out=[];doc.querySelectorAll("line").forEach(n=>out.push(normalize({type:"line",x1:num(n.getAttribute("x1")),y1:num(n.getAttribute("y1")),x2:num(n.getAttribute("x2")),y2:num(n.getAttribute("y2"))})));doc.querySelectorAll("rect").forEach(n=>out.push(normalize({type:"rect",x:num(n.getAttribute("x")),y:num(n.getAttribute("y")),w:Math.abs(num(n.getAttribute("width"))),h:Math.abs(num(n.getAttribute("height")))})));doc.querySelectorAll("circle").forEach(n=>out.push(normalize({type:"circle",cx:num(n.getAttribute("cx")),cy:num(n.getAttribute("cy")),r:Math.abs(num(n.getAttribute("r")))})));return out}
$("svgInput").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const shapes=parseSvg(await f.text());if(!shapes.length)throw new Error();snapshot();state.shapes.push(...shapes);state.selectedIds=[];hideProperties();fitAll();status(`${shapes.length} SVG-Element(e) importiert`)}catch{status("SVG konnte nicht gelesen werden")}e.target.value=""};

function layerName(s){const tech=(s.cam?.technology||"Keine").replace(/[^A-Za-z0-9]/g,"_").toUpperCase(),ct=resolvedContourType(s).toUpperCase(),bv=s.cam?.bevel?.enabled?`_BEVEL_${Math.round(s.cam.bevel.angle)}_${s.cam.bevel.side.toUpperCase()}`:"";return`${tech}_${ct}${bv}`}
function dxfPair(c,v){return`${c}\n${v}\n`}function dxfLine(x1,y1,x2,y2,layer){return dxfPair(0,"LINE")+dxfPair(8,layer)+dxfPair(10,fmt(x1))+dxfPair(20,fmt(-y1))+dxfPair(30,0)+dxfPair(11,fmt(x2))+dxfPair(21,fmt(-y2))+dxfPair(31,0)}function dxfCircle(s,layer){return dxfPair(0,"CIRCLE")+dxfPair(8,layer)+dxfPair(10,fmt(s.cx))+dxfPair(20,fmt(-s.cy))+dxfPair(30,0)+dxfPair(40,fmt(s.r))}
function makeDxf(){const layers=[...new Set(state.shapes.map(layerName))];let out=dxfPair(0,"SECTION")+dxfPair(2,"HEADER")+dxfPair(9,"$ACADVER")+dxfPair(1,"AC1009")+dxfPair(0,"ENDSEC")+dxfPair(0,"SECTION")+dxfPair(2,"TABLES")+dxfPair(0,"TABLE")+dxfPair(2,"LAYER")+dxfPair(70,layers.length);for(const l of layers)out+=dxfPair(0,"LAYER")+dxfPair(2,l)+dxfPair(70,0)+dxfPair(62,7)+dxfPair(6,"CONTINUOUS");out+=dxfPair(0,"ENDTAB")+dxfPair(0,"ENDSEC")+dxfPair(0,"SECTION")+dxfPair(2,"ENTITIES");for(const s of state.shapes){const l=layerName(s);if(s.type==="line")out+=dxfLine(s.x1,s.y1,s.x2,s.y2,l);if(s.type==="circle")out+=dxfCircle(s,l);if(s.type==="rect"){out+=dxfLine(s.x,s.y,s.x+s.w,s.y,l);out+=dxfLine(s.x+s.w,s.y,s.x+s.w,s.y+s.h,l);out+=dxfLine(s.x+s.w,s.y+s.h,s.x,s.y+s.h,l);out+=dxfLine(s.x,s.y+s.h,s.x,s.y,l)}}out+=dxfPair(0,"ENDSEC")+dxfPair(0,"EOF");return out}
$("dxfBtn").onclick=()=>{if(!state.shapes.length){status("Keine Geometrie für DXF");return}download("cutai-export-v06-r12.dxf",makeDxf(),"application/dxf");status(`${state.shapes.length} CAD-Objekt(e) als DXF exportiert`)};

function geomForPlan(s){if(s.type==="rect")return{type:"closed_polyline",points:[[s.x,s.y],[s.x+s.w,s.y],[s.x+s.w,s.y+s.h],[s.x,s.y+s.h],[s.x,s.y]]};if(s.type==="circle")return{type:"circle",center:[s.cx,s.cy],radius:s.r};if(s.type==="line")return{type:"line",from:[s.x1,s.y1],to:[s.x2,s.y2]}}
$("camPlanBtn").onclick=()=>{const operations=state.shapes.map(s=>({id:s.id,order:s.cam.order,technology:s.cam.technology,contourType:resolvedContourType(s),direction:s.cam.direction,startPoint:s.cam.startPoint,leadIn:s.cam.leadIn,leadOut:s.cam.leadOut,bevel:{enabled:!!s.cam.bevel.enabled,angle:clamp(s.cam.bevel.angle,0,50),side:s.cam.bevel.side,type:s.cam.bevel.type,land:s.cam.bevel.land},geometry:geomForPlan(s)})).sort((a,b)=>a.order-b.order);download("cutai-cam-plan-v06.json",JSON.stringify({schema:"cutai-cam-plan/0.6",units:"mm",bevelAngleLimitDeg:50,postprocessor:null,note:"Neutraler CAM-Plan. Keine Maschinen-/M-Codes.",operations},null,2),"application/json");status("CAM-Plan mit Fasenparametern exportiert")};

render();
})();